
<% 
asp_write("<table id=client_list border=0  cellpadding=1 cellspacing=0  bordercolor=#CCCCCC bgcolor=#FFFFFF>");
asp_write("<tr height=40>")
    asp_write("<td width=20 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLEINDEXText","s")
    asp_write("</strong></td>")
    asp_write("<td width=133 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLEHOSTNAMEText","s")
    asp_write("</strong></td>")
    asp_write("<td width=93 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLEIPText","s")
    asp_write("</strong></td>")
    asp_write("<td width=123 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLEMACText","s");
    asp_write("</strong></td>")
    asp_write("<td width=123 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLECONNECTYPEText","s")
    asp_write("</strong></td>")
    asp_write("<td width=100 align=center class=tabdata><strong><FONT color=#000000>")
        tcWebApi_get("String_Entry","LANDTABLEEXPIREText","s")
    asp_write("</strong></td>")
asp_write("</tr>")

if tcWebApi_staticGet("LanHost_Entry0", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("1")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry0", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry0", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry0", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry0", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry0", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry0", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry1", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("2")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry1", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry1", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry1", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry1", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry1", "ExpireDay","s")
	asp_write("days ");
        tcWebApi_staticGet("LanHost_Entry1", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry2", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("3")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry2", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry2", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry2", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry2", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry2", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry2", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry3", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("4")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry3", "HostName","s")
    asp_write("</td>");
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry3", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry3", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry3", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry3", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry3", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry4", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("5")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry4", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry4", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry4", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry4", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry4", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry4", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry5", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("6")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry5", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry5", "IP","s");
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry5", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry5", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry5", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry5", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry6", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("7")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry6", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry6", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry6", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry6", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry6", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry6", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry7", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("8")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry7", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry7", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry7", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry7", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry7", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry7", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry8", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("9")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry8", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry8", "IP","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry8", "MAC","s");
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry8", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >");
        tcWebApi_staticGet("LanHost_Entry8", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry8", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if

if tcWebApi_staticGet("LanHost_Entry9", "IP","h") <> "N/A" then
    asp_write("<tr>")
    asp_write("<td align=center class=topborderstyle >")
        asp_write("10")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_Get("LanHost_Entry9", "HostName","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry9", "IP","s")
    asp_write("</td>");
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry9", "MAC","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry9", "InterfaceType","s")
    asp_write("</td>")
    asp_write("<td align=center class=topborderstyle >")
        tcWebApi_staticGet("LanHost_Entry9", "ExpireDay","s")
	asp_write("days ")
        tcWebApi_staticGet("LanHost_Entry9", "ExpireTime","s")
    asp_write("</td>")
asp_write("</tr>")
end if
asp_write("</table>")

if tcWebApi_staticGet("LanHost_Entry10", "IP","h") <> "N/A" then
    asp_write("<input type=button name=MORE  value=More... onClick=javascript:window.open('/cgi-bin/more_client_list.asp')>")
end if 
   
%>

