#!/bin/sh

echo -e "Content-Type: text/html\n"
echo -e "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">"
echo -e "<html><head>\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9; IE=8; IE=7; IE=EDGE\">\n<meta http-equiv=Content-Script-Type content=text/javascript>\n<meta http-equiv=Content-Style-Type content=text/css>\n<meta http-equiv=Content-Type content=\"text/html; charset=utf-8\">\n<link rel=\"stylesheet\" href=\"/style.css\" type=\"text/css\" tppabs=\"http://192.168.1.1/css/style.css\">"
echo -e "<script language=\"JavaScript\">\tvar virstrtmp = top.ary_strings;\n\tvar vir_obj = {};\n\tfor(var i=0; virstrtmp[i][0] != \"\";i++) vir_obj[virstrtmp[i][0]]=virstrtmp[i][1];\n</script>"
echo -e "	</head>"
echo -e "<script language=\"JavaScript\">"
echo -e "function showTable(id,data){"
echo -e "   selectNum = document.getElementById(\"read_level\").value;"
echo -e "	var html = [\"<table id=sys_log>\"];"
echo -e "	var level = 0"
echo -e "	for(var i =0; i<data.length; i++){"
echo -e "		if(data[i][2] != \"N/A\"){"
echo -e "			var levelList = [\"Emergency\",\"Alert\",\"Critical\",\"Error\",\"Warning\",\"Notice\",\"Info\",\"Debug\"]"
echo -e "			for(var count=0; count<8; count++){"
echo -e "				if(data[i][2].match(levelList[count])!=null) {"
echo -e "					level=count;"
echo -e "					}"
echo -e "				}"
echo -e "			if(selectNum >= level){ "
echo -e "				html.push(\"<tr>\");"
echo -e "				for(var j=0; j<(data[i].length); j++){"
echo -e "					html.push(data[i][j]);"
echo -e "				}"
echo -e "				html.push(\"</tr>\");"
echo -e "			}"
echo -e "		}"
echo -e "	}"
echo -e "	html.push(\"</table>\");"
echo -e "	document.getElementById(id).innerHTML = html.join('');"
echo -e "}"
echo -e "	var tableData = ["
tail -n 50 /var/log/foxsys.log > /var/log/tmpfoxsys.log
infile=/var/log/tmpfoxsys.log
i=0
while read line;do
#	date=`echo $line | cut -d "," -f 1`
#	time=`echo $line | cut -d "," -f 2`
#	level=`echo $line | cut -d "," -f 3`
#	system=`echo $line | cut -d "," -f 4`
#	message=`echo $line | cut -d "," -f 5`
#	eval $(echo $line | awk -F"," '{printf("date=%s; time=%s; level=%s;",$1,$2,$3)}')
	eval $(echo $line | awk -F" " '{printf("category=%s; ipaddr=%s; time=%s",$1,$2,$5)}')
	eval $(echo $category | awk -F"." '{printf("system=%s; level=%s",$1,$2)}')
	#len=`expr ${#category} + ${#ipaddr} + 2`
	#message=`echo -e $line | cut -c $len-`
	date=`echo -e $line | cut -d " " -f 3-4`
	message=`echo -e $line | cut -d " " -f 6-`

	if [ "$i" != 0 ];then
		echo -e ","
	fi
	echo -e "	[\"<td width='15%'>$date</td>\",\"<td width='15%'>$time</td>\",\"<td width='18%'>$level</td>\",\"<td width='15%'>$system</td>\",\"<td width='37%'>$message</td>\"]"
	i=1
done < $infile

rm /var/log/tmpfoxsys.log
echo -e "];"
echo -e "function save_log(){\n\tvar cfg='/cgi-bin/foxsys.log';\n\tvar code='location.assign(\"' + cfg + '\")';\n\teval(code);\n}"
echo -e "function Refresh_log(){\n\tdocument.location.href=\"/cgi-bin/status_log.cgi\";\n}"
echo -e "</script>"

echo -e "<body marginwidth=\"0\" marginheight=\"0\">"
echo -e "<form>"
echo -e "	<div id=\"pagestyle\">"
echo -e "		<div id=\"content_right\">"	
echo -e "			<div id=\"block1\">"
echo -e "				<table width=\"640px\" border=\"0\"  cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" style=\"margin:5px 0;\"> "
echo -e "					<tr height=\"25px\">"
echo -e "   <td align=\"left\" class=\"title-main\" style=\"padding-left:20px;\">\n<script>document.writeln(vir_obj[\"SystemLogText0\"]);</script></td>"
echo -e "   </tr>"
echo -e "   </table>"
echo -e "   <table  width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">"
echo -e "       <tbody>"
echo -e "       <tr height=\"40px\" id=\"buttoncolor\">"
echo -e "       <td align=\"left\" class=\"tabdata\" style=\"padding-left:20px;\">"
echo -e "			<a class=\"button1\" onClick=\"save_log();\">\n<script>document.writeln(vir_obj[\"SystemLogText1\"]);</script></a>"
echo -e "       </td>"
echo -e "       </tr>"
echo -e "       </tbody>"
echo -e "  	</table>"  
echo -e "   </div>"	
echo -e "			<div id=\"block1\">"
echo -e "				<table width=\"640px\" border=\"0\"  cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\" style=\"margin:5px 0;\"> "
echo -e "					<tr height=\"25px\">"
echo -e "						<td width=\"250px\" align=\"left\" class=\"title-main\" style=\"padding-left:20px;background:#e6e6e6;\">\n<script>document.writeln(vir_obj[\"SystemLogSetReadingText\"]);</script></td>"
echo -e "					</tr>"
echo -e "				</table>"
echo -e "				<table  width=\"640\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">"
echo -e "				<tbody>"
echo -e "					<tr height=\"30px\">"
echo -e "						<td width=\"250\" id=\"XS2\" class=\"tabdata\" align=\"left\" style=\"font-size:13px;padding-left:20px;\">\n<script>document.writeln(vir_obj[\"SystemLogReadingText\"]);</script></td>"
echo -e "						<td class=\"tabdata\" align=\"left\">"
echo -e "							<select name=\"read_level\" id=\"read_level\" onchange=\"showTable('div_log',tableData)\">"
echo -e "								<option value=\"0\" id=\"XS17\">\n<script>document.writeln(vir_obj[\"SystemLogEmergencyText\"]);</script></option>"
echo -e "								<option value=\"1\" id=\"XS18\">\n<script>document.writeln(vir_obj[\"SystemLogAlertText\"]);</script></option>"
echo -e "								<option value=\"2\" id=\"XS19\">\n<script>document.writeln(vir_obj[\"SystemLogCriticalText\"]);</script></option>"
echo -e "								<option value=\"3\" id=\"XS20\">\n<script>document.writeln(vir_obj[\"SystemLogErrorText\"]);</script></option>"
echo -e "								<option value=\"4\" id=\"XS21\">\n<script>document.writeln(vir_obj[\"SystemLogWarningText\"]);</script></option>"
echo -e "								<option value=\"5\" id=\"XS22\">\n<script>document.writeln(vir_obj[\"SystemLogNoticeText\"]);</script></option>"
echo -e "								<option value=\"6\" id=\"XS23\">\n<script>document.writeln(vir_obj[\"SystemLogInformationalText\"]);</script></option>"
echo -e "								<option value=\"7\" id=\"XS24\" selected>\n<script>document.writeln(vir_obj[\"SystemLogDebugText\"]);</script></option>"
echo -e "							</select>"
echo -e "						</td>"
echo -e "					</tr>"
echo -e "				</tbody></table>"
echo -e "			</div>"

echo -e "			<div class=\"cfglist\">"
echo -e "				<table style=\"margin:5px 0;\">"
echo -e "					<tbody><tr><th colspan=\"5\" id=\"XS3\" class=\"tableTitle\">\n<script>document.writeln(vir_obj[\"SystemLogText\"]);</script></th></tr>"
echo -e "					</tbody></table>"
echo -e "				<table>"
echo -e "					<tbody>"
echo -e "					<tr>"
echo -e "						<td id=\"XS4\" width=\"15%\"><strong>\n<script>document.writeln(vir_obj[\"SystemLogDateText\"]);</script></strong></td>"
echo -e "						<td id=\"XS5\" width=\"15%\"><strong>\n<script>document.writeln(vir_obj[\"SystemLogTimeText\"]);</script></strong></td>"
echo -e "						<td id=\"XS6\" width=\"18%\"><strong>\n<script>document.writeln(vir_obj[\"SystemLogLevelText\"]);</script></strong></td>"
echo -e "						<td id=\"XS7\" width=\"15%\"><strong>\n<script>document.writeln(vir_obj[\"SystemLogSystemText\"]);</script></strong></td>"
echo -e "						<td id=\"XS8\" width=\"37%\"><strong>\n<script>document.writeln(vir_obj[\"SystemLogActionText\"]);</script></strong></td>"
echo -e "					</tr>"
echo -e "				</tbody></table>"
echo -e "				<div id=\"div_log\" style=\"overflow-y: auto; overflow-x:hidden;height: 400px;\">"
echo -e "				</div>"
echo -e "			</div>"
echo -e "		</div>"
echo -e "	</div>"
echo -e "				<table  width=\"690px\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">"
echo -e "                           <tr height=\"30\">"
echo -e " 					<td width=\"20\">&nbsp;</td>"
echo -e " 					<td width=\"250\">&nbsp;</td>"
echo -e " 					<td width=\"420\"></td>"
echo -e " 				</tr>"	
echo -e " 				<tr>"
echo -e " 					<td align=center colSpan=3 style=\"background-color:transparent;font-family: Arial,Helvetica,sans-serif;color:#404040;\"><font size=2>\n<script>document.writeln(vir_obj[\"CopyrightText\"]);</script></font></td>"
echo -e " 				</tr>"
echo -e "                           <tr height=\"10\">"
echo -e " 					<td width=\"20\">&nbsp;</td>"
echo -e " 					<td width=\"250\">&nbsp;</td>"
echo -e " 					<td width=\"420\"></td>"
echo -e " 				</tr>"	
echo -e " 			</table>"

echo -e "</form>"
echo -e "</body>"
echo -e "<script language=JavaScript>"
echo -e "	showTable('div_log',tableData);"
echo -e "</script>"
echo -e "</html>"
