#!/bin/bash
#
# watchdog
#
# Run as a cron job to keep an eye on what_to_monitor which should always
# be running. Restart what_to_monitor and send notification as needed.
#
# This needs to be run as root or a user that can start system services.
#
# Revisions: 0.1 (20100506), 0.2 (20100507)

#Client sessions settings
foxtmp=/var/tmp/foxtmp
foxtrack=/proc/foxconn/blocklist
mkdir -p $foxtmp
foxblklist=$foxtmp/foxblklist
echo -n "" >> $foxblklist
connthreshold=1000
blktime=300

if [ $1 -eq 1 ] ; then
	iptables -A INPUT -m connlimit --connlimit-above $connthreshold -j DROP
	iptables -A FORWARD -m connlimit --connlimit-above $connthreshold -j DROP
fi

if [ $1 -eq 0 ] ; then
	exec < $foxblklist
	while read line
	do
		delIP=`echo $line | cut -d "=" -f 1`
		iptables -D INPUT -s $delIP -j DROP
		iptables -D FORWARD -s $delIP -j DROP
		sed -in '/$delIP/d' $foxblklist
	done
	iptables -D INPUT -m connlimit --connlimit-above $connthreshold -j DROP
	iptables -D FORWARD -m connlimit --connlimit-above $connthreshold -j DROP
fi

while [ $1 -eq 1 ] 
do
	#Check client sessions
	infile=$foxtrack
	exec < $infile
	while read clientIP
	do
		existlist=0	
		BAKIFS=$IFS                    # save current input field separator
		IFS=$(echo -en "\n\b")         #   and change it.
		exec 3<&0                      # save current stdin
		exec 0<"$foxblklist"           #   and change it to read from file.

		while read blockIP
		do
			blockIP=`echo $blockIP | cut -d "=" -f 1`
			if [ "$blockIP" = "$clientIP" ]; then
				existlist=1
			fi
		done
		if [ $existlist -eq 0 ]; then
			echo -n "$clientIP=" >> $foxblklist
			date +%s >> $foxblklist
			iptables -I INPUT -s $clientIP -j DROP
			iptables -I FORWARD -s $clientIP -j DROP
		fi
		exec 0<&3                      # restore previous stdin.
		IFS=$BAKIFS                    #   and IFS.
	done
	
	exec < $foxblklist
	while read line
	do
		duringtime=`expr $(date +%s) - $(echo $line | cut -d "=" -f 2)`
		delIP=`echo $line | cut -d "=" -f 1`

		if [ $duringtime -gt $blktime ]; then
			iptables -D INPUT -s $delIP -j DROP
			iptables -D FORWARD -s $delIP -j DROP
			sed -in '/$delIP/d' $foxblklist
		fi
	done

	sleep 2
done

